---
title: "Fysologisk testing arbeidskrav 1"
format: html
editor: visual
---

## Arbeidskrav 1

```{r} 
#| echo: false

library(ggplot2)
library(readxl)
library(knitr)
library(dplyr)


data <- read_excel("Fysologisk testing.xlsx")

ggplot(data, aes(x = factor(timepoint), y = vo2max, fill = factor(timepoint))) +
  geom_boxplot() +
  labs(title = "Vo2max by Timepoint",
       x = "Timepoint",
       y = "vo2max") +
  theme_minimal() +
theme(plot.title = element_text(hjust = 0.51)) +
  
  ggtitle("Vo2max by Timepoint") 
```

```{r}
#| echo: false

library(readxl)
library(dplyr)

data <- read_excel("Fysologisk testing.xlsx")


summary_table <- data %>%
  summarise(
    Variabel = "Alder",
    Gjennomsnitt = mean(age),
    Standardavvik = sd(age),
    Median = median(age),
    Minimum = min(age),
    Maksimum = max(age)
  ) %>%
  bind_rows(data %>%
              summarise(
                Variabel = "Bodyheight",
                Gjennomsnitt = mean(bodyheight),
                Standardavvik = sd(bodyheight),
                Median = median(bodyheight),
                Minimum = min(bodyheight),
                Maksimum = max(bodyheight)
              )) %>%
  bind_rows(data %>%
              summarise(
                Variabel = "Vekt",
                Gjennomsnitt = mean(vekt),
                Standardavvik = sd(vekt),
                Median = median(vekt),
                Minimum = min(vekt),
                Maksimum = max(vekt)
              )) %>%
  bind_rows(data %>%
              summarise(
                Variabel = "Vo2max",
                Gjennomsnitt = mean(vo2max),
                Standardavvik = sd(vo2max),
                Median = median(vo2max),
                Minimum = min(vo2max),
                Maksimum = max(vo2max)
              )) %>%
  bind_rows(data %>%
              summarise(
                Variabel = "w.max",
                Gjennomsnitt = mean(w.max),
                Standardavvik = sd(w.max),
                Median = median(w.max),
                Minimum = min(w.max),
                Maksimum = max(w.max)
              )) %>%
  bind_rows(data %>%
              summarise(
                Variabel = "MAOD.a",
                Gjennomsnitt = mean(MAOD.a),
                Standardavvik = sd(MAOD.a),
                Median = median(MAOD.a),
                Minimum = min(MAOD.a),
                Maksimum = max(MAOD.a)
              ))

echo = FALSE
print(summary_table)
```



jalla tekst
```{r} #UTreging av CV}
# Utrenging av CV

library(readxl)
library(dplyr)

data <- read_excel("Fysologisk testing.xlsx")

cv_results <- data %>%
  group_by(id) %>%
  summarize(cv_vo2max = sd(vo2max, na.rm = TRUE) / mean(vo2max, na.rm = TRUE) * 100)

print(cv_results)

mean_cv <- mean(cv_results$cv_vo2max, na.rm = TRUE)

print(mean_cv)

cv_wmax_results <- data %>%
  group_by(id) %>%
  summarize(cv_wmax = sd(w.max, na.rm = TRUE) / mean(w.max, na.rm = TRUE) * 100)

mean_cv_wmax <- mean(cv_wmax_results$cv_wmax, na.rm = TRUE)

print(cv_wmax_results)

print(mean_cv_wmax)

cv_maoda_results <- data %>%
  group_by(id) %>%
  summarize(cv_maoda = sd(MAOD.a, na.rm = TRUE) / mean(MAOD.a, na.rm = TRUE) * 100)

mean_cv_maoda <- mean(cv_maoda_results$cv_maoda, na.rm = TRUE)

print(cv_maoda_results)

print(mean_cv_maoda)

std_dev_by_id <- data %>%
  group_by(id) %>%
  summarize(std_dev_vo2max = sd(vo2max))

for (i in 1:nrow(std_dev_by_id)) {
  std_dev_by_id$std_dev_vo2max[i] <- std_dev_by_id$std_dev_vo2max[i] * 0.2
}
print(std_dev_by_id)

mean_std_dev <- mean(std_dev_by_id$std_dev_vo2max)

print(mean_std_dev)
print(std_dev_by_id)

mean_std_dev_0.2 <- mean(std_dev_by_id$std_dev_vo2max_0.2)

print(mean_std_dev_0.2)

if ("std_dev_vo2max_0.2" %in% colnames(std_dev_by_id)) {

  mean_std_dev_0.2 <- mean(std_dev_by_id$std_dev_vo2max_0.2)
  
  print(mean_std_dev_0.2)
} else {
  print("Kolonnen std_dev_vo2max_0.2 eksisterer ikke i dataframen.")
}

std_dev_wmax_by_id <- aggregate(data$w.max, by = list(data$id), FUN = function(x) sd(x) * 0.2)

colnames(std_dev_wmax_by_id) <- c("ID", "std_dev_wmax_0.2")

print(std_dev_wmax_by_id)

mean_std_dev_wmax_0.2 <- mean(std_dev_wmax_by_id$std_dev_wmax_0.2)

print(mean_std_dev_wmax_0.2)

std_dev_maod_a_by_id <- aggregate(data$MAOD.a, by = list(data$id), FUN = function(x) sd(x) * 0.2)

colnames(std_dev_maod_a_by_id) <- c("ID", "std_dev_MAODa_0.2")

print(std_dev_maod_a_by_id)

mean_std_dev_MAODa_0.2 <- mean(std_dev_MAODa_by_id$std_dev_MAODa_0.2)

print(mean_std_dev_MAODa_0.2)

mean_std_dev_MAOD_a_by_id <- mean(data$std_dev_MAODa_0.2, na.rm = TRUE)

data <- na.omit(data)

mean_std_dev_MAODa_0.2 <- mean(data$std_dev_MAODa_0.2, na.rm = TRUE)

print(mean_std_dev_MAODa_0.2)

data <- data %>%
  group_by(id) %>%
  mutate(std_dev_MAODa_0.2 = sd(MAOD.a) * 0.2)

mean_std_dev_MAODa_0.2 <- mean(data$std_dev_MAODa_0.2, na.rm = TRUE)

print(mean_std_dev_MAODa_0.2)

```
Denne skal regne ut CV bare er en ny kode
```{r}
# Utrenging av CV

library(readxl)
library(dplyr)

data <- read_excel("Fysologisk testing.xlsx")

# Calculate CV for vo2max
cv_results <- data %>%
  group_by(id) %>%
  summarize(cv_vo2max = sd(vo2max, na.rm = TRUE) / mean(vo2max, na.rm = TRUE) * 100)

print(cv_results)

mean_cv <- mean(cv_results$cv_vo2max, na.rm = TRUE)

print(mean_cv)

# Calculate CV for w.max
cv_wmax_results <- data %>%
  group_by(id) %>%
  summarize(cv_wmax = sd(w.max, na.rm = TRUE) / mean(w.max, na.rm = TRUE) * 100)

print(cv_wmax_results)

mean_cv_wmax <- mean(cv_wmax_results$cv_wmax, na.rm = TRUE)

print(mean_cv_wmax)

# Calculate CV for MAOD.a
cv_maoda_results <- data %>%
  group_by(id) %>%
  summarize(cv_maoda = sd(MAOD.a, na.rm = TRUE) / mean(MAOD.a, na.rm = TRUE) * 100)

print(cv_maoda_results)

mean_cv_maoda <- mean(cv_maoda_results$cv_maoda, na.rm = TRUE)

print(mean_cv_maoda)

# Calculate adjusted standard deviation for vo2max
std_dev_by_id <- data %>%
  group_by(id) %>%
  summarize(std_dev_vo2max = sd(vo2max))

for (i in 1:nrow(std_dev_by_id)) {
  std_dev_by_id$std_dev_vo2max[i] <- std_dev_by_id$std_dev_vo2max[i] * 0.2
}

print(std_dev_by_id)

mean_std_dev <- mean(std_dev_by_id$std_dev_vo2max, na.rm = TRUE)

print(mean_std_dev)
print(std_dev_by_id)

# Check for the existence of the column std_dev_vo2max_0.2
if ("std_dev_vo2max_0.2" %in% colnames(std_dev_by_id)) {
  mean_std_dev_0.2 <- mean(std_dev_by_id$std_dev_vo2max_0.2, na.rm = TRUE)
  print(mean_std_dev_0.2)
} else {
  print("Kolonnen std_dev_vo2max_0.2 eksisterer ikke i dataframen.")
}

# Calculate adjusted standard deviation for w.max
std_dev_wmax_by_id <- aggregate(data$w.max, by = list(data$id), FUN = function(x) sd(x) * 0.2)

colnames(std_dev_wmax_by_id) <- c("ID", "std_dev_wmax_0.2")

print(std_dev_wmax_by_id)

mean_std_dev_wmax_0.2 <- mean(std_dev_wmax_by_id$std_dev_wmax_0.2, na.rm = TRUE)

print(mean_std_dev_wmax_0.2)

# Calculate adjusted standard deviation for MAOD.a
std_dev_maod_a_by_id <- aggregate(data$MAOD.a, by = list(data$id), FUN = function(x) sd(x) * 0.2)

colnames(std_dev_maod_a_by_id) <- c("ID", "std_dev_MAODa_0.2")

print(std_dev_maod_a_by_id)

mean_std_dev_MAODa_0.2 <- mean(std_dev_maod_a_by_id$std_dev_MAODa_0.2, na.rm = TRUE)

print(mean_std_dev_MAODa_0.2)

# Calculate mean of adjusted standard deviation for MAOD.a
if ("std_dev_MAODa_0.2" %in% colnames(data)) {
  mean_std_dev_MAODa_0.2_data <- mean(data$std_dev_MAODa_0.2, na.rm = TRUE)
  print(mean_std_dev_MAODa_0.2_data)
} else {
  print("Kolonnen std_dev_MAODa_0.2 eksisterer ikke i dataframen.")
}

```

Denne lager tabell
```{r}
# Last inn readxl-pakken for å lese Excel-filer
library(readxl)

# Les data fra Excel-filen
data <- read_excel("Fysologisk testing.xlsx")

# Funksjon for beregning av CV
calculate_cv <- function(x) {
  cv <- sd(x) / mean(x)
  return(cv)
}

# Fjern rader med manglende verdier i rpe.max, vo2max og MAOD.a
data <- na.omit(data[, c("id", "rpe.max", "vo2max", "MAOD.a")])

# Sjekk om det er data tilgjengelig
if (nrow(data) > 0) {
  # Grupper data etter id og beregn CV for rpe.max, vo2max og MAOD.a
  cv_data <- aggregate(. ~ id, data=data, FUN=calculate_cv)
  
  # Print resultatene
  print(cv_data)
} else {
  cat("Ingen data tilgjengelig for beregning av CV.")
}

```





caht tekst

```{r}
#| echo: false

library(readxl)
library(dplyr)

data <- read_excel("Fysologisk testing.xlsx")

cv_results <- data %>%
  group_by(id) %>%
  summarize(cv_vo2max = sd(vo2max, na.rm = TRUE) / mean(vo2max, na.rm = TRUE) * 100)

mean_cv <- mean(cv_results$cv_vo2max, na.rm = TRUE)

cv_wmax_results <- data %>%
  group_by(id) %>%
  summarize(cv_wmax = sd(w.max, na.rm = TRUE) / mean(w.max, na.rm = TRUE) * 100)

mean_cv_wmax <- mean(cv_wmax_results$cv_wmax, na.rm = TRUE)

cv_maoda_results <- data %>%
  group_by(id) %>%
  summarize(cv_maoda = sd(MAOD.a, na.rm = TRUE) / mean(MAOD.a, na.rm = TRUE) * 100)

mean_cv_maoda <- mean(cv_maoda_results$cv_maoda, na.rm = TRUE)

std_dev_by_id <- data %>%
  group_by(id) %>%
  summarize(std_dev_vo2max = sd(vo2max))

for (i in 1:nrow(std_dev_by_id)) {
  std_dev_by_id$std_dev_vo2max[i] <- std_dev_by_id$std_dev_vo2max[i] * 0.2
}

std_dev_by_id$std_dev_vo2max_0.2 <- std_dev_by_id$std_dev_vo2max * 0.2  

mean_std_dev <- mean(std_dev_by_id$std_dev_vo2max)

mean_std_dev_0.2 <- mean(std_dev_by_id$std_dev_vo2max_0.2)

std_dev_wmax_by_id <- aggregate(data$w.max, by = list(data$id), FUN = function(x) sd(x) * 0.2)

colnames(std_dev_wmax_by_id) <- c("ID", "std_dev_wmax_0.2")

mean_std_dev_wmax_0.2 <- mean(std_dev_wmax_by_id$std_dev_wmax_0.2)

std_dev_maod_a_by_id <- aggregate(data$MAOD.a, by = list(data$id), FUN = function(x) sd(x) * 0.2)

colnames(std_dev_maod_a_by_id) <- c("ID", "std_dev_MAODa_0.2")

mean_std_dev_MAODa_0.2 <- mean(std_dev_maod_a_by_id$std_dev_MAODa_0.2)

mean_std_dev_MAOD_a_by_id <- mean(data$std_dev_MAODa_0.2, na.rm = TRUE)

data <- na.omit(data)

mean_std_dev_MAODa_0.2 <- mean(data$std_dev_MAODa_0.2)

data <- data %>%
  group_by(id) %>%
  mutate(std_dev_MAODa_0.2 = sd(MAOD.a) * 0.2)

mean_std_dev_MAODa_0.2 <- mean(data$std_dev_MAODa_0.2, na.rm = TRUE)

result_table <- data.frame(
  Variable = c("VO2max", "W.max", "MAOD.a"),
  `Mean Coef. of Variation (0.2)` = c(mean_cv, mean_cv_wmax, mean_cv_maoda),
  `Mean Std. Deviation (0.2)` = c(mean_std_dev, mean_std_dev_wmax_0.2, mean_std_dev_MAODa_0.2)
)

result_table$Variable <- gsub("^\\d+\\.?\\d*\\s*", "", result_table$Variable)

result_table <- result_table[!(result_table$Variable %in% c("MAOD.a (after NA removal)", "MAOD.a (after calculation)")), ]

rownames(result_table) <- NULL

colnames(result_table) <- c("Variable", "Mean Coef. of Variation (0.2)", "Mean Std. Deviation (0.2)")

print(result_table)

```

```{r}
#| echo: false

library(readxl)
library(knitr)
library(dplyr)

data <- read_excel("Fysologisk testing.xlsx")


cv_results <- data %>%
  group_by(id) %>%
  summarize(cv_vo2max = sd(vo2max, na.rm = TRUE) / mean(vo2max, na.rm = TRUE) * 100)

print(cv_results)

mean_cv <- mean(cv_results$cv_vo2max, na.rm = TRUE)

print(mean_cv)

cv_wmax_results <- data %>%
  group_by(id) %>%
  summarize(cv_wmax = sd(w.max, na.rm = TRUE) / mean(w.max, na.rm = TRUE) * 100)

mean_cv_wmax <- mean(cv_wmax_results$cv_wmax, na.rm = TRUE)

print(cv_wmax_results)

print(mean_cv_wmax)

cv_maoda_results <- data %>%
  group_by(id) %>%
  summarize(cv_maoda = sd(MAOD.a, na.rm = TRUE) / mean(MAOD.a, na.rm = TRUE) * 100)

mean_cv_maoda <- mean(cv_maoda_results$cv_maoda, na.rm = TRUE)

print(cv_maoda_results)

print(mean_cv_maoda)

std_dev_by_id <- data %>%
  group_by(id) %>%
  summarize(std_dev_vo2max = sd(vo2max))

for (i in 1:nrow(std_dev_by_id)) {
  std_dev_by_id$std_dev_vo2max[i] <- std_dev_by_id$std_dev_vo2max[i] * 0.2
}

# Create a new column std_dev_vo2max_0.2
std_dev_by_id$std_dev_vo2max_0.2 <- std_dev_by_id$std_dev_vo2max * 0.2

print(std_dev_by_id)

mean_std_dev <- mean(std_dev_by_id$std_dev_vo2max)

print(mean_std_dev)
print(std_dev_by_id)

mean_std_dev_0.2 <- mean(std_dev_by_id$std_dev_vo2max_0.2)

print(mean_std_dev_0.2)

if ("std_dev_vo2max_0.2" %in% colnames(std_dev_by_id)) {

  mean_std_dev_0.2 <- mean(std_dev_by_id$std_dev_vo2max_0.2)
  
  print(mean_std_dev_0.2)
} else {
  print("Kolonnen std_dev_vo2max_0.2 eksisterer ikke i dataframen.")
}

std_dev_wmax_by_id <- aggregate(data$w.max, by = list(data$id), FUN = function(x) sd(x) * 0.2)

colnames(std_dev_wmax_by_id) <- c("ID", "std_dev_wmax_0.2")

print(std_dev_wmax_by_id)

mean_std_dev_wmax_0.2 <- mean(std_dev_wmax_by_id$std_dev_wmax_0.2)

print(mean_std_dev_wmax_0.2)

# Create std_dev_MAODa_by_id dataframe
std_dev_MAODa_by_id <- aggregate(data$MAOD.a, by = list(data$id), FUN = function(x) sd(x) * 0.2)
colnames(std_dev_MAODa_by_id) <- c("ID", "std_dev_MAODa_0.2")

print(std_dev_MAODa_by_id)

mean_std_dev_MAODa_0.2 <- mean(std_dev_MAODa_by_id$std_dev_MAODa_0.2)

print(mean_std_dev_MAODa_0.2)

# Sett resultatene i en tabell
result_table <- data.frame(
  ID = std_dev_by_id$id,
  CV_VO2max = cv_results$cv_vo2max,
  CV_Wmax = cv_wmax_results$cv_wmax,
  CV_MAODa = cv_maoda_results$cv_maoda,
  Std_Dev_VO2max_0.2 = std_dev_by_id$std_dev_vo2max_0.2,
  Std_Dev_Wmax_0.2 = std_dev_wmax_by_id$std_dev_wmax_0.2,
  Std_Dev_MAODa_0.2 = std_dev_MAODa_by_id$std_dev_MAODa_0.2
)

# Skriv ut tabellen
print(kable(result_table))
```


```{r}
#| echo: false

library(readxl)
library(dplyr)

data <- read_excel("Fysologisk testing.xlsx")

calculate_cv_and_sd <- function(df, variable) {
  df %>%
    group_by(id) %>%
    summarise(cv = sd({{variable}}, na.rm = TRUE) / mean({{variable}}, na.rm = TRUE) * 100,
              std_dev_0.2 = sd({{variable}}, na.rm = TRUE) * 0.2)
}


cv_vo2max_results <- calculate_cv_and_sd(data, vo2max)
cv_wmax_results <- calculate_cv_and_sd(data, w.max)
cv_maoda_results <- calculate_cv_and_sd(data, MAOD.a)


print(cv_vo2max_results)
print(cv_wmax_results)
print(cv_maoda_results)


mean_cv_vo2max <- mean(cv_vo2max_results$cv, na.rm = TRUE)
mean_cv_wmax <- mean(cv_wmax_results$cv, na.rm = TRUE)
mean_cv_maoda <- mean(cv_maoda_results$cv, na.rm = TRUE)

mean_std_dev_vo2max <- mean(cv_vo2max_results$std_dev_0.2, na.rm = TRUE)
mean_std_dev_wmax <- mean(cv_wmax_results$std_dev_0.2, na.rm = TRUE)
mean_std_dev_maoda <- mean(cv_maoda_results$std_dev_0.2, na.rm = TRUE)


print(mean_cv_vo2max)
print(mean_cv_wmax)
print(mean_cv_maoda)

print(mean_std_dev_vo2max)
print(mean_std_dev_wmax)
print(mean_std_dev_maoda)

```

